export const INGESTION_SERVICE = Symbol("INGESTION_SERVICE");
export const VECTORIZATION_SERVICE = Symbol("VECTORIZATION_SERVICE");
export const SEARCH_SERVICE = Symbol("SEARCH_SERVICE");
export const FEATURE_EXTRACTION_SERVICE = Symbol("FEATURE_EXTRACTION_SERVICE");

export const PRODUCT_MAPPER = Symbol("PRODUCT_MAPPER");

export const PRODUCT_REPOSITORY = Symbol("PRODUCT_REPOSITORY");
